DROP TABLE ALQUILER;
DROP TABLE VIDEO;


CREATE TABLE VIDEO 
(
  ID NUMBER NOT NULL,
  NAME VARCHAR2(255 BYTE), 
  DURATION NUMBER,
  CONSTRAINT VIDEO_PK PRIMARY KEY (ID)

);

CREATE TABLE ALQUILER 
(
  ID NUMBER NOT NULL,
  VIDEO_ID2 NUMBER,
  USER_NAME VARCHAR2(255 BYTE), 
  CONSTRAINT ALQUILER_PK PRIMARY KEY (ID),
  CONSTRAINT FK_VIDEO2 FOREIGN KEY (VIDEO_ID2) REFERENCES VIDEO(ID)
);

INSERT INTO VIDEO(ID,NAME,DURATION) values (1,'Harry Potter',120);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (2,'Orgullo y Prejuicio',200);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (3,'Furia de Titanes',140);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (4,'Piratas del Caribe',100);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (5,'Avatar',150);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (6,'El Señor de los Anillos',130);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (7,'Sense 8',200);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (8,'Game of Thrones',160);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (9,'Drake and Josh',120);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (10,'The Crown',150);
INSERT INTO VIDEO (ID,NAME,DURATION) VALUES (11,'La Mujer Maravilla',100);


INSERT INTO ALQUILER (ID,VIDEO_ID2,USER_NAME) VALUES (1,1,'Jack');
INSERT INTO ALQUILER (ID,VIDEO_ID2,USER_NAME) VALUES (2,1,'Juan');
INSERT INTO ALQUILER (ID,VIDEO_ID2,USER_NAME) VALUES (3,2,'Pedro');
INSERT INTO ALQUILER (ID,VIDEO_ID2,USER_NAME) VALUES (4,5,'Jack');
INSERT INTO ALQUILER (ID,VIDEO_ID2,USER_NAME) VALUES (5,10,'Nick');
INSERT INTO ALQUILER (ID,VIDEO_ID2,USER_NAME) VALUES (6,11,'Jack');
INSERT INTO ALQUILER (ID,VIDEO_ID2,USER_NAME) VALUES (7,4,'Sara');
INSERT INTO ALQUILER (ID,VIDEO_ID2,USER_NAME) VALUES (8,7,'Jack');
INSERT INTO ALQUILER (ID,VIDEO_ID2,USER_NAME) VALUES (9,7,'Jack');


COMMIT;


